/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "CabMatEvy",
    "x": 1181.3162887397393,
    "z": 1411.4105692144853
  },
  {
    "name": "0_Fiery_0",
    "x": 1154.476599681862,
    "z": 1373.48325287868
  }
]
