/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "0_Fiery_0",
    "x": 1176.9998365023887,
    "z": 1431.6888543680004
  },
  {
    "name": "CabMatEvy",
    "x": 1154.1855172802311,
    "z": 1376.1917148178159
  }
]
